version: '3.5'

services:
  nginx:
    container_name: project-nginx
    depends_on:
      - wordpress
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs

  db:
    container_name: project-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project_cms
    image: mariadb
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - './data/db:/var/lib/mysql:delegated'

  wordpress:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: project-wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_NAME: project_cms
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: password
    # image: docker.pkg.github.com/OWNER/REPOSITORY/project:wordpress
    image: project:wordpress
    restart: always
    volumes:
      - ./src:/var/www/html:rw,cached
      - ./config/php:/usr/local/etc/php/conf.d
  # composer:
  #   container_name: project-composer
  #   image: composer/composer
  #   restart: 'no'
  #   volumes:
  #     - ./src:/var/www/html:rw,cached
  #   working_dir: /var/www/html
  # mailcatcher:
  #   image: schickling/mailcatcher
  #   ports:
  #     - '1025:1025'
  #     - '1080:1080'
  #   environment:
  #     MAILCATCHER_PORT: 1025
  #   networks:
  #     - localwp
