version: '3.5'

services:
  db:
    image: mysql:5.7
    container_name: project_db
    # volumes:
    #   - data:/var/lib/mysql
    # ports:
    #   - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project_cms
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - localwp

  wordpress:
    container_name: project_wordpress
    image: wordpress:latest
    ports:
      - '8080:80'
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: project_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: project_cms
    working_dir: /var/www/html
    volumes:
      - ./data:/data
      - ./web:/app
    networks:
      - localwp

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
    environment:
      MAILCATCHER_PORT: 1025
    networks:
      - localwp

networks:
  localwp:
    name: localwp

volumes:
  data: {}
